print ("primer cambio en git - todo correcto")
print ("creacion de .gitignore -  todo correcto")
print("verificacion de git diff - todo correcto")
print("Probar git checkout e indicar HEAD - todo correcto")
print ("Aplicacion de git reset --hard y git reflog - todo correcto")
print ("Creacion de tag, ver tags y movernos entre tags - todo correcto")
print ("Creacion de rama con git branch y movernos entre ramas con git switch - Todo correcto")
print ("Aplicacion de git diff -rama-, git merge - Todo correcto")
print ("Aplicacion de git stash, git stash list, git stash pop, git stash drop - Todo correcto")
print ("aplicacion de git branch -d -rama-, para borrar la rama de login y su localizacion nuevamente- Todo correcto")
print ("Probar que nuestra maquina realmente este conectada al repositorio de github - Listo ")
print ("Aplicar git remote add origin git@github.com:Jescad29/Gitflow_Prueba.git - Listo")
print ("Aplicar git push -u origin main para subir mi repositorio - Todo correcto")
print ("Aplicar git pull para obtene cambios del repositorio remoto a mi repositorio local")
print ("aplicacion de git fetch para descargar el historial de cambios")

print ("Para iniciar git flow primero checamos si tenemo alguna version con git flow version y si no nos sale")
print ("Utilizamos brew install git-flow")
print ("Para iniciarlo es git flow init y nos posicionara en la rama develop, para abrir otra rama ")
print ("Por ejemplo una que despliegue los cambios a la rama develop abrimos una rama feature con el comando git flow feature start -nombre-")
print ("Para desplegar la version en la rama main utilizamos git flow release start -nombre-")
print ("Ambas ramas se cierran sustituyendo finish por start en el comando")
print ("Ya nada mas los subimos a nuestro git hub con push")
