print ("primer cambio en git - todo correcto")
print ("creacion de .gitignore -  todo correcto")
print("verificacion de git diff - todo correcto")
print("Probar git checkout e indicar HEAD - todo correcto")
print ("Aplicacion de git reset --hard y git reflog - todo correcto")
print ("Creacion de tag, ver tags y movernos entre tags - todo correcto")
print ("Creacion de rama con git branch y movernos entre ramas con git switch - Todo correcto")
print ("Aplicacion de git merge - Todo correcto")
print ("Aplicacion de git stash, git stash list, git stash pop, git stash drop -")